# This file may be used to create an environment using:
# $ conda env create --name <env> --file environment.yml
# platform: linux-64
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.6
  - pybedtools=0.9.0
  - pysam=0.21.0
  - cyvcf2=0.30.16
  - scikit-learn=1.2.2
  - pandas=2.0.0
  - matplotlib=3.7.1
  - seaborn=0.13.2
