# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
name: SAVANA-env
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.9.6
  - pybedtools=0.9.0
  - pysam=0.20.0
  - cyvcf2=0.30.16
  - scikit-learn=1.2.2
  - pandas=2.0.0
